sonar.projectKey=luckyPerson06_FitnessApp
sonar.organization=luckyperson06
sonar.host.url=https://sonarcloud.io

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.junit.reportPaths=target/surefire-reports
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

sonar.java.source=17
sonar.java.target=17

sonar.exclusions=**/MyApp.java,**/dto/**,**/exception/**,**/config/**,**/mapper/**